apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  replicas: 2
  minReadySeconds: 60
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      name: myapp
  template:
    metadata:
      labels:
        name: myapp
    spec:
      containers:
      - name: test
        image: siddaks.azurecr.io/myapp
        imagePullPolicy: Always

---
kind: Service
apiVersion: v1
metadata:
  name: myapp
spec:
  selector:
    name: myapp
  ports:
  - name: port1
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
