apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: siddakspipeline 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: siddakspipeline 
    spec:
      containers:
        - name: siddakspipeline 
          image: siddaks.azurecr.io/siddakspipeline
          ports:
          - containerPort: 8080